### ISSUE TITLE
Add test cases for publish/request using various types for Node<T>

### ISSUE THREAD

**Issue by quietlychris** [quietlychris/bissel#10]
During some testing, I recently encountered a bug with deserializing values of type `bool`, when the same code seemed to work while using `Strings` or `Coordinates`. This error consistenetly tracked down to the `from_bytes()?` function in the Host deserialization process for `GenericRhizaMsg`, but I haven't had time to track it down yet. Both that, and adding some test cases against various different types that satisfy the `Message` trait might be worth looking into.

**Comment by quietlychris** [comment]
I think I just ran into this same issue for a struct `MyValues { x: isize, y: isize }` as well, so not limited to boolean or single-value data structures.

**Comment by quietlychris** [comment]
Here's the stack trace with `RUST_BACKTRACE=1` enabled: 
```
thread 'tokio-runtime-worker' panicked at 'Hit the end of buffer, expected more data', src/host.rs:234:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/std/src/panicking.rs:577:5
   1: core::panicking::panic_fmt
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/core/src/panicking.rs:110:14
   2: core::panicking::panic_display
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/core/src/panicking.rs:65:5
   3: rhiza::host::process::{{closure}}::{{closure}}
             at ./src/host.rs:234:25
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/core/src/future/mod.rs:84:19
   5: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.29/src/instrument.rs:272:9
   6: rhiza::host::process::{{closure}}
             at ./src/host.rs:217:1
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/core/src/future/mod.rs:84:19
   8: rhiza::host::Host::start::{{closure}}::{{closure}}
             at ./src/host.rs:137:49
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/core/src/future/mod.rs:84:19
  10: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/core/src/future/future.rs:123:9
  11: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/core.rs:161:17
  12: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/loom/std/unsafe_cell.rs:14:9
  13: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/core.rs:151:13
  14: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:461:19
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/core/src/panic/unwind_safe.rs:271:9
  16: std::panicking::try::do_call
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/std/src/panicking.rs:485:40
  17: __rust_try
  18: std::panicking::try
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/std/src/panicking.rs:449:19
  19: std::panic::catch_unwind
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/std/src/panic.rs:136:14
  20: tokio::runtime::task::harness::poll_future
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:449:18
  21: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:98:27
  22: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:53:15
  23: tokio::runtime::task::raw::poll
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/raw.rs:113:5
  24: tokio::runtime::task::raw::RawTask::poll
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/raw.rs:70:18
  25: tokio::runtime::task::LocalNotified<S>::run
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/mod.rs:343:9
  26: tokio::runtime::thread_pool::worker::Context::run_task::{{closure}}
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/thread_pool/worker.rs:443:21
  27: tokio::coop::with_budget::{{closure}}
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:106:9
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/std/src/thread/local.rs:413:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/std/src/thread/local.rs:389:9
  30: tokio::coop::with_budget
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:99:5
  31: tokio::coop::budget
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/coop.rs:76:5
  32: tokio::runtime::thread_pool::worker::Context::run_task
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/thread_pool/worker.rs:419:9
  33: tokio::runtime::thread_pool::worker::Context::run
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/thread_pool/worker.rs:386:24
  34: tokio::runtime::thread_pool::worker::run::{{closure}}
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/thread_pool/worker.rs:371:17
  35: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/macros/scoped_tls.rs:61:9
  36: tokio::runtime::thread_pool::worker::run
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/thread_pool/worker.rs:368:5
  37: tokio::runtime::thread_pool::worker::Launch::launch::{{closure}}
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/thread_pool/worker.rs:347:45
  38: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/blocking/task.rs:42:21
  39: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/core.rs:161:17
  40: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/loom/std/unsafe_cell.rs:14:9
  41: tokio::runtime::task::core::CoreStage<T>::poll
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/core.rs:151:13
  42: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:461:19
  43: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/core/src/panic/unwind_safe.rs:271:9
  44: std::panicking::try::do_call
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/std/src/panicking.rs:485:40
  45: __rust_try
  46: std::panicking::try
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/std/src/panicking.rs:449:19
  47: std::panic::catch_unwind
             at /rustc/777bb86bcdbc568be7cff6eeeaaf81a89b4aa50b/library/std/src/panic.rs:136:14
  48: tokio::runtime::task::harness::poll_future
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:449:18
  49: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:98:27
  50: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/harness.rs:53:15
  51: tokio::runtime::task::raw::poll
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/raw.rs:113:5
  52: tokio::runtime::task::raw::RawTask::poll
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/raw.rs:70:18
  53: tokio::runtime::task::UnownedTask<S>::run
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/task/mod.rs:379:9
  54: tokio::runtime::blocking::pool::Inner::run
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/blocking/pool.rs:264:17
  55: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/chrism/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.14.0/src/runtime/blocking/pool.rs:244:17
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by quietlychris** [comment]
Okay, so this is coming from the Host `from_bytes()` deserialization function, where `postcard` is throwing a `DeserializeUnexpectedEnd` error (docs [here](https://docs.rs/postcard/latest/postcard/enum.Error.html)). 

The failure can be reproduced run the binary `start_host`, the creating the following connection: 
```rust
fn main() {
    let addr = "127.0.0.1:25000".parse::<std::net::SocketAddr>().unwrap();
    let mut node: Node<UserInput> = NodeConfig::new("pose").host_addr(addr).build().unwrap();
    node.connect().unwrap();
    node.publish_to("boolean",true).unwrap();
    let output: bool = node.request("boolean").unwrap();
    dbg!(output);
}
```
This should write a standard log file to `logs/`, which has the following: 
```
ERROR process{stream=PollEvented { io: Some(TcpStream { addr: 127.0.0.1:25000, peer:
 127.0.0.1:50250, fd: 16 }) } db=Db {
    Tree: "__sled__default" contents: Tree:
        PageCache { max: 4 free: Mutex { data: [] } }
        level 0:
                3: Node { prefix_len: 0, next: None, merging_child: None, merging: false, lo: [], hi: [], data: Index(Index { keys: [[]], pointers: [
2] }) }

        level 1:
                2: Node { prefix_len: 0, next: None, merging_child: None, merging: false, lo: [], hi: [], data: Leaf(Leaf { keys: [], values: [] }) }
} count=Mutex { data: 0 }}: rhiza::host: Had received RhizaMsg of 12 bytes, Error: Hit the end of buffer, expected more data
```
Remember, this is deserializing a `GenericRhizaMsg` first, not a typed RhizaMsg
---
It seems that the issue occurs due to `postcard` not liking the way that the single-byte values (`bool`, `u8`, `i8`) are included. Next steps are to verify that the messages being received by the Hosts are exactly the same ones being transmitted by the Nodes. This might be something that could be better done in the actual code by using functions, and then added as unit tests.
